# To run use command "docker-compose --env-file voting.env up"
version: '3.8'
services:
  backend:
    image: "voting:0.0.1"
    container_name: "spring-boot-app"
    build:
      context: .
      dockerfile: application/Dockerfile
    ports:
      - "8080:8080"
    env_file: "voting.env"
    depends_on:
      db:
        condition: service_healthy



  db:
    image: "postgres:15.3"
    container_name: "postgres"
    ports:
      - "5432:5432"
    env_file: "voting.env"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 10s
      timeout: 3s
      retries: 5


  frontend:
    build: ./react-app
    container_name: "react-app"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    ports:
      - "3000:3000"

