# To run use command "docker-compose --env-file voting.env up"
version: '3.8'
services:
  backend:
    image: "voting:0.0.1"
    container_name: "spring-boot-app"
    build:
      context: .
      dockerfile: application/Dockerfile
    ports:
      - "8080:8080"
    env_file: "voting.env"
    networks:
      - voting-network

  db:
    image: "postgres:15.3"
    container_name: "postgres"
    ports:
      - "5432:5432"
    env_file: "voting.env"
    networks:
      - voting-network

  frontend:
    build: ./react-app
    container_name: "react-app"
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080
    ports:
      - "80:3000"
    stdin_open: true
    tty: true
    networks:
      - voting-network

networks:
  voting-network:
    name: "voting-network"
