# To run use command "docker-compose --env-file voting.env up"
version: '3.8'
services:
  spring-boot-app:
    image: "voting:0.0.1"
    container_name: "spring-boot-app"
    build: 
      context: .
      dockerfile: application/Dockerfile
      tags:
        - "voting:0.0.1"
    ports:
      - "${APP_PORT}:8080"
    env_file: "voting.env"

  postgres:
    image: "postgres:15.3"
    container_name: "postgres"
    ports:
      - "${DB_PORT}:5432"
    env_file: "voting.env"

  react-app:
    build: ./react-app
    container_name: "react-app"
    ports:
      - "${REACT_APP_PORT}:3000"
    env_file: "react-app/frontend.env"
    stdin_open: true
    tty: true
