version: '3.8'
services:
  app:
    image: "voting:0.0.1"
    container_name: "voting-app"
    build: 
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - "voting:0.0.1"
    ports:
      - "8080:8080"
  db:
    image: "postgres:15.3"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    

