# To run use command "docker-compose --env-file voting.env up"
version: '3.8'
services:
  app:
    image: voting-app:0.0.1
    container_name: voting-app
    build: 
      context: .
      dockerfile: docker/app.Dockerfile
      tags:
        - voting-app:0.0.1
    ports:
      - ${APP_PORT}:8080
    env_file: voting.env
    networks:
      - web-network
      - db-network

  db:
    image: postgres:15.3
    container_name: db
    ports:
      - 5432:5432
    env_file: voting.env
    networks:
      - db-network

  web:
    image: voting-web:0.0.1
    container_name: voting-web
    build:
      context: .
      dockerfile: docker/web.Dockerfile
      tags:
        - voting-web:0.0.1
    ports:
      - ${WEB_PORT}:3000
    env_file: voting.env
    networks:
      - web-network


networks:
  web-network:
    name: web-network
  db-network:
    name: db-network